### PR TITLE
AutoShoot

### PR DESCRIPTION
**Pull request by ThisTestUser**
It's basically a triggerbot for bows, and was requested in #210. The mod was made in 1.15.2, but it should still work in the latest version. Note that it's currently broken for crossbows.

I also have the 1.12 version of the mod if you need to backport this to 1.12/1.8.

### CODE REVIEW

**Comment by AeroCarmel** [comment]
please wurst gods may you add this to your client

**Comment by wurstisgood** [comment]
can anyone send the downloadable .zip file if anyone added it(With AutoShoot)

**Comment by wurstisgood** [comment]
> please wurst gods may you add this to your client

**you can add it yourself but i too dont know how to add it :(**

**Comment by Alexander01998** [comment]
@wurstisgood Here you go.
[Wurst-Client-AutoShoot-MC1.15.2.zip](https://github.com/Wurst-Imperium/Wurst7/files/5550378/Wurst-Client-AutoShoot-MC1.15.2.zip)
Please test it and tell me how it works.

**Comment by AeroCarmel** [comment]
> @wurstisgood Here you go.
> [Wurst-Client-AutoShoot-MC1.15.2.zip](https://github.com/Wurst-Imperium/Wurst7/files/5550378/Wurst-Client-AutoShoot-MC1.15.2.zip)
> Please test it and tell me how well it works.

Thanks i'll look at this version of it in a little bit

**Comment by AeroCarmel** [comment]
> It's basically a triggerbot for bows, and was requested in #210. The mod was made in 1.15.2, but it should still work in the latest version. Note that it's currently broken for crossbows.
> 
> I also have the 1.12 version of the mod if you need to backport this to 1.12/1.8.

I was growing impatient and decided to compile your code into a version for myself. I may be stupid but it doesn't look like its going to be compatible with 1.16 there are some errors that i'm trying to fix XD but you didn't add alot of commenting so i'm going in blind.

**Comment by wurstisgood** [comment]
> @wurstisgood Here you go.
> [Wurst-Client-AutoShoot-MC1.15.2.zip](https://github.com/Wurst-Imperium/Wurst7/files/5550378/Wurst-Client-AutoShoot-MC1.15.2.zip)
> Please test it and tell me how well it works.

ok thank you so much,I will surely test it

**Comment by wurstisgood** [comment]
> @wurstisgood Here you go.
> [Wurst-Client-AutoShoot-MC1.15.2.zip](https://github.com/Wurst-Imperium/Wurst7/files/5550378/Wurst-Client-AutoShoot-MC1.15.2.zip)
> Please test it and tell me how well it works.

it is not working perfectly, it is not working unless you manually start aiming and then shoot for 1 time but after some time it stops again

**Comment by wurstisgood** [comment]
> > It's basically a triggerbot for bows, and was requested in #210. The mod was made in 1.15.2, but it should still work in the latest version. Note that it's currently broken for crossbows.
> > I also have the 1.12 version of the mod if you need to backport this to 1.12/1.8.
> 
> I was growing impatient and decided to compile your code into a version for myself. I may be stupid but it doesn't look like this version is going to be compatible with 1.16 there are some errors that i'm trying to fix XD but you didn't add alot of commenting so i'm going in blind.

yes there are some errors and it is not compatible with 1.16.3

**Pull request closed without merging**
