### PR TITLE
AntiFabric Bypass

### PR DESCRIPTION
**Pull request by ThisTestUser**
This feature allows Wurst to bypass servers that kick Fabric users. Since Fabric doesn't tell the server what mods it is using, some servers may opt to prevent Fabric clients from connecting.

Note: The mixin must be done from ClientConnection.class, otherwise not all the packets will be captured.

### CODE REVIEW

**Comment by andrew121410** [comment]
Hopefully, this get's merged soon.

**Comment by Alexander01998** [comment]
Can you give some examples of servers that do this?

**Comment by ThisTestUser** [comment]
Most server owners won't block fabric, but they will install a plugin that alerts them when fabric users connect.
Here's a plugin I found that blocks fabric: https://www.spigotmc.org/resources/lib-hates-mods.78202/

**Comment by Alexander01998** [comment]
This has been merged into the `v7.7-mc1.16.3` branch and will be in master when v7.7 is released.

**Comment by Alexander01998** [comment]
I have created a wiki page for VanillaSpoof at https://wiki.wurstclient.net/vanillaspoof.
If you know any other plugins that this works with, please add them there.

**Pull request closed without merging**
