### PR TITLE
fix sneaking for glide

### PR DESCRIPTION
**Pull request by Lamby777**
## Description
I originally intended to make this branch for fixing a bunch of issues with sneaking in certain hacks, but it would probably be too many, so I'm just gonna do 1 hack at a time. Today I added a new checkbox for Glide to temporarily disable the effects when crouching. It acts similar to pressing crouch in Creative Mode.

### CODE REVIEW

**Comment by Lamby777** [comment]
still important, though idr if this got added by other people later on anyway

**Comment by Alexander01998** [comment]
Hey @Lamby777,

Thanks for the reminder! Just had a look, and it seems like this PR has some significant conflicts and formatting issues that need to be resolved before it's ready for a merge.

If the sneaking fix hasn't been added by anyone else yet and you still believe it's important, I encourage you to resolve those conflicts and tidy up the formatting. Once that's done, give me a shout and I'll take another look at it.

**Comment by Lamby777** [comment]
> Hey @Lamby777,
> 
> Thanks for the reminder! Just had a look, and it seems like this PR has some significant conflicts and formatting issues that need to be resolved before it's ready for a merge.
> 
> If the sneaking fix hasn't been added by anyone else yet and you still believe it's important, I encourage you to resolve those conflicts and tidy up the formatting. Once that's done, give me a shout and I'll take another look at it.

Yeah, it's been a while since I posted this, and back then I remember formatting issues were a huge pain because they'd always cause massive merge conflicts, so thanks for adding that one formatter in the build process (forgot what it's called, "spotless" or something)

**Comment by Lamby777** [comment]
I think this PR was made from a different repo I have since deleted, and not the other fork I currently work on... If I'm getting this right, you can't change a PR's source branch, so I [made a new PR for this](https://github.com/Wurst-Imperium/Wurst7/pull/919). Turns out the feature was mostly already re-implemented on this fork, but I forgot to add the `addSetting` call for the new checkbox... :/

image

**Pull request closed without merging**
