### PR TITLE
Autofarm enhancements

### PR DESCRIPTION
**Pull request by maomihz**
## Description
* Consider using the best fortune tools when harvesting crops
* Fix the problem of not harvesting 2 block tall kelp plants (the top most block is "KelpBlock" while the bottoms are "KelpPlantBlock")
* Address the issue #169
  * Add bamboo support
  * Allow user to select a list of blocks to farm, so that they can exclude any crops / blocks.

### CODE REVIEW

**Comment by procrafter820** [comment]
can you please code for adding setting of speed in killaura and triggerbot

**Comment by procrafter820** [comment]
good but why @alexander01998 not assigned

**Comment by Alexander01998** [comment]
@procrafter820 has been banned for spamming @mentions.

**Comment by wurstisgood** [comment]
when will this be implemented?

**Comment by JamesTheAwesomeDude** [comment]
> Consider using the best fortune tools when harvesting crops

There are at least 2 good ways to solve this

- Add Fortune support to AutoTool
- Make AutoFarm switch back to your previous weapon after replanting

You could also code Fortune support directly into AutoFarm, but I think either of those ^ would be better

**Pull request closed without merging**
