### PR TITLE
Added an AutoTotem Hack

### PR DESCRIPTION
**Pull request by andevo**
## Description
What have you added and what does it do? (Alternatively, what have you fixed and how does it work?)

AutoTotem will automatically moves a totem to your offhand. Used [ForgeHax](https://github.com/fr1kin/ForgeHax) as a resource for creation.

## (Optional) screenshots / videos
If applicable, add screenshots or videos to help explain your pull request.

AutoTotem Demo

### CODE REVIEW

**Comment by Alexander01998** [comment]
Merged in c0d0fb3796bef6d11f7c0dec6519b997e5bd93c1. No idea why GitHub didn't mark this as merged.

**Comment by andevo** [comment]
Already merged. c0d0fb3

**Comment by Alexander01998** [comment]
Hey @andevo, can I include your AutoTotem GIF on the Wurst Wiki? https://wiki.wurstclient.net/autototem

**Comment by andevo** [comment]
@Alexander01998 Yes. I would like to see that. Thank you for asking.

**Pull request closed without merging**
