### PR TITLE
Added Basic M.L.G 

### PR DESCRIPTION
**Pull request by gurachan**
the preview is here

https://www.youtube.com/watch?v=cUqwSNVbDFc

It's not perfect but the success rate is high enough for me xD  I hope @Alexander01998 will implement it and fix it make it perfect xD

### CODE REVIEW

**Comment by wurstisgood** [comment]
wow great

**Comment by hrmorley34** [comment]
One thing I have noticed is that if you land on a change of elevation it can place the water on the lower block when the player's hitbox lands on the upper block.

**Comment by Rainerr123** [comment]
> One thing I have noticed is that if you land on a change of elevation it can place the water on the lower block when the player's hitbox lands on the upper block.

"basic"

**Comment by wurstisgood** [comment]
how to add it

**Comment by hrmorley34** [comment]
You have to build the jar from source (`./gradlew build`); [here's a build I've just done (with updated upstream)](https://github.com/Wurst-Imperium/Wurst7/files/5423855/Wurst-Client-v7.6.1-MC1.16.3.zip)

**Comment by wurstisgood** [comment]
> You have to build the jar from source (`./gradlew build`); [here's a build I've just done (with updated upstream)](https://github.com/Wurst-Imperium/Wurst7/files/5423855/Wurst-Client-v7.6.1-MC1.16.3.zip)

i downloaded it but still automlg is not showing in hack list @hrmorley34

**Comment by hrmorley34** [comment]
Sorry, I forgot that the source doesn't have it added to the hacklist; I've added [a pull request](https://github.com/Dj-jom2x/Wurst7/pull/1) to fix this. 
[*Here* is a hopefully functional build.](https://github.com/Wurst-Imperium/Wurst7/files/5427625/Wurst-Client-v7.6.1-MC1.16.3%2BAutoMLG.zip)

**Comment by wurstisgood** [comment]
> Sorry, I forgot that the source doesn't have it added to the hacklist; I've added [a pull request](https://github.com/Dj-jom2x/Wurst7/pull/1) to fix this.
> [_Here_ is a hopefully functional build.](https://github.com/Wurst-Imperium/Wurst7/files/5427625/Wurst-Client-v7.6.1-MC1.16.3%2BAutoMLG.zip)

yes it works now thanks

**Comment by TheAwesome98-Real** [comment]
> Sorry, I forgot that the source doesn't have it added to the hacklist; I've added [a pull request](https://github.com/Dj-jom2x/Wurst7/pull/1) to fix this.
> [_Here_ is a hopefully functional build.](https://github.com/Wurst-Imperium/Wurst7/files/5427625/Wurst-Client-v7.6.1-MC1.16.3%2BAutoMLG.zip)

if thats on your own repository can you not jsut merge it? or is it not done? confused

**Pull request closed without merging**
