### PR TITLE
Add ShearAuraHack

### PR DESCRIPTION
**Pull request by ShayBox**
## Description
What have you added and what does it do? (Alternatively, what have you fixed and how does it work?)  
Added ShearAuraHack, based on FeedAuraHack, but shears sheep.

## (Optional) screenshots / videos
If applicable, add screenshots or videos to help explain your pull request.  
https://youtu.be/8wKsnGwdauc

### CODE REVIEW

**Comment by FlorianMichael** [comment]
nice

**Comment by sudofox** [comment]
Would be great to see this merged in.

Any chance to add smth similar to AutoFish/AutoTool's options to automatically switch another pair of shears once the old one breaks/once the current one is about to break?

**Comment by InfinitePower563** [comment]
cool

**Comment by sudofox** [comment]
@Alexander01998 This one in particular would be really great to have right about now. I have far too many sheep...

**Review by InfinitePower563 — APPROVED** [review]
Nice addition, could be useful.

**Review by FlorianMichael — APPROVED** [review]

**Comment by ShayBox** [comment]
How is this still open

**Pull request closed without merging**
