### PR TITLE
Added Prefix Support

### PR DESCRIPTION
**Pull request by Alsdrouf**
## Description
I added a prefix support that permanent and change all the super with the new prefix. And it avoid using the '/' as prefix

### CODE REVIEW

**Review by AndrewBruhMoment — CHANGES_REQUESTED** [review]
The code looks good! I will test it out for you and see what results I can get using this and if there are any bugs. Consider changing the super for the .say command to include the prefix that the user is using to clear up any confusion that may occur, otherwise, everything seems great.

**Comment by AndrewBruhMoment** [comment]
Your command works on my pc! One thing that I have noticed is that sometimes doing commands with the prefix of "/" breaks, but otherwise it seems ready. When using "/", some commands get executed server-side and could come up as a red flag for any moderator. I would disable the use of "/" for one's prefix using something like: 

Replace 
`CmdProcessor.setPrefix(args[0])`
to
`       
 if(!args[0].equals("/")) {
        	CmdProcessor.setPrefix(args[0]);
        }else {
        	throw new CmdSyntaxError("Can't use / It doesn't Work Try again");
        }`

**Comment by Alsdrouf** [comment]
I don't know if I can change the super

**Review by AndrewBruhMoment — APPROVED** [review]

**Comment by AndrewBruhMoment** [comment]
@Alsdrouf This is what the kids call a "True Bruh Moment." I should have said this earlier when I found it, but I was still testing.
Replacing
`for(String line : syntax)
			ChatUtils.message(line)`
to 
`for(String line : cmd.getSyntax())
			ChatUtils.message(line.replace(".", CmdProcessor.getPrefix()));`

and 

Replace
`for(String line : cmd.getSyntax())
			ChatUtils.message(line);`
to
`for(String line : syntax)
			ChatUtils.message(line.replace(".", CmdProcessor.getPrefix()));`

I'm so sorry you had to go through the pain of replacing the suppers.

**Comment by Alsdrouf** [comment]
Maybe If you finish the syntax string with point it will not replace it too?

**Comment by Alsdrouf** [comment]
I am trying to make it percistent but that's hard

**Comment by AndrewBruhMoment** [comment]
I believe this issue can be solved by replacing 
`.replace(".", CmdProcessor.getPrefix())`
to 
`replaceFirst("\\.", CmdProcessor.getPrefix())`

Things might have changed since I last saw the code, so this may not exactly work.

**Comment by Alsdrouf** [comment]
I think now it's good but maybe I destroy some codes and do bad things like removing some final var

**Comment by Alsdrouf** [comment]
I will change the code to make it more clean

**Comment by Alsdrouf** [comment]
I think I clean up the code maybe need a review of the code

**Pull request closed without merging**
