### PR TITLE
Add Anti Fireball Hack

### PR DESCRIPTION
**Pull request by duggavo**
## Description
AntiFireball automatically repels fireballs by hitting them. Useful in Bedwars.

### CODE REVIEW

**Comment by duggavo** [comment]
> prferrably in such a way so it flies the direction it came from
As far as I know, that's not possible without teleporting the player, which could cause issue with blocks and would be blocked by anticheats anyway

**Comment by Cyclopropinon** [comment]
> > prferrably in such a way so it flies the direction it came from

> As far as I know, that's not possible without teleporting the player, which could cause issue with blocks and would be blocked by anticheats anyway

@duggavo 
well the player could walk towards the predicted position, to redirect it. no need to teleport
(_there could be a setting (de)activating it_)

**Comment by Ebopeep** [comment]
Yo I'm new in dis world can someone take my hand and walk me through it

**Comment by Cyclopropinon** [comment]
@Ebopeep what world?

**Pull request closed without merging**
