### PR TITLE
Check Line of sight in Aim Assist

### PR DESCRIPTION
**Pull request by TejasLamba2006**
## Added
- Check Line of sight in Aim Assist 

**New Features:**
- `AimAssistHack`: Added a new option to enable line of sight checking. When enabled, the target will be set to null if there's an obstruction between the player and the target.

### Summary by CodeRabbit

- New Feature: Added a "Check Line of Sight" option in the Aim Assist feature. When enabled, it ensures that the aim assist only targets entities that are directly visible, improving the accuracy and effectiveness of the feature.
- Improvement: Updated the Auto Sword feature to better identify attackable entities. This enhancement ensures that the feature only interacts with valid targets, increasing its efficiency and reliability.

### CODE REVIEW

**Review by Alexander01998 — CHANGES_REQUESTED** [review]
Hi @TejasLamba2006, thanks for your contributions! However, could you please split these changes into separate pull requests? That way it's much easier to label, review and potentially merge each change. A combined pull request with unrelated changes can be hard to keep track of, as GitHub isn't really designed to work this way. Appreciate your understanding here!

**Comment by TejasLamba2006** [comment]
✔️The build successfully compiles and works, checked personally

**Comment by TejasLamba2006** [comment]
@Alexander01998, is the pull okay now?

**Review by Alexander01998 — APPROVED** [review]

**Comment by Alexander01998** [comment]
> * 95-100: The `triggerBotHack` is no longer being disabled in the `onEnable` method. If this is intentional and the `triggerBotHack` is compatible with the `AimAssistHack`, then this change is fine. If not, this could lead to conflicts between the hacks.

Thanks @coderabbitai, I missed that one. Fix commit coming up.

**Comment by Alexander01998** [comment]
@TejasLamba2006 It's good now. I've adjusted the "Check line of sight" description, since AimAssist can't actually make you reach through blocks, and changed the setting to be enabled by default. Just so you know, I'm going to merge this pull request into the v7.38 branch, so GitHub won't mark it as merged until Wurst 7.38 is released.

**Comment by TejasLamba2006** [comment]
Cool ! Looking forward to contribute more, If you have a discord I would live to talk

**Pull request merged**
