### PR TITLE
Added Packet Canceller

### PR DESCRIPTION
**Pull request by MrNereof**
## Description
Cancellation of various types of packets.

### CODE REVIEW

**Comment by nofh428** [comment]
@MrNereof what does this do, can we get screenshots?

**Comment by MrNereof** [comment]
@nofh428 this hack cancel selected packet types sent from client to server. This means that specific packets will not be sent. I don't know what to screenshot.

**Comment by nofh428** [comment]
@MrNereof thanks

**Comment by nofh428** [comment]
@MrNereof can you go to https://github.com/Wurst-Imperium/Wurst7/issues/358 and help this dude to make a pull request I dont know how

**Comment by JamesTheAwesomeDude** [comment]
> this hack cancel selected packet types sent from client to server. This means that specific packets will not be sent

@MrNereof what _use_ does this have? Does it allow you to dodge hits? Glitch through walls? Avoid hunger draining? Backtrack actions you regret?

In particular, does this duplicate what utility the [`Blink`](https://www.google.com/search?q=wurst+client+%22blink%22) hack provides?

**Comment by MrNereof** [comment]
@JamesTheAwesomeDude this hack can be used in much duplication glitch. It's based on a module from [spidermod](https://github.com/ionar2/spidermod).

For example: https://youtu.be/NCugTSbUrFo

**Comment by FlorianMichael** [comment]
It would be better if you would develop a system for the packets that automatically goes through all Minecraft packets and adds a setting for them

**Comment by MrNereof** [comment]
Bump

**Comment by Alexander01998** [comment]
Closing because this PacketCanceller implementation has become severely outdated and is not in line with best practices. Please feel free to submit a new pull request if you have an updated version.

**Pull request closed without merging**
