### PR TITLE
Anti flykick

### PR DESCRIPTION
**Pull request by BenCat07**
## Description
Added a Checkbox for preventing kicks for flying in vanilla.
This Option will set your velocity to -0.05 every 2 seconds in order to prevent being kicked for flying on vanilla servers.

### CODE REVIEW

**Comment by BenCat07** [comment]
I've just noticed that this might cause undesirable behavior when flying Downwards, fixing. 
You should probably use a squash merge if you decide to merge it, as this should have been in the first commit in the first place.

**Comment by BenCat07** [comment]
Potential TODOs:
- Shift back up the 0.05 blocks the following tick (i can also make it an option, but that makes the menu look a bit clustered, up to @Alexander01998 if it should or shouldn't be added, i'll add it if desired)

**Comment by KTibow** [comment]
Hope I'm not being too annoying by asking this, but how could I build this into a jar to use?

**Comment by BenCat07** [comment]
> Hope I'm not being too annoying by asking this, but how could I build this into a jar to use?

this is currently outdated, as the main branch changed the corrosponding files within the months of inactivity

**Comment by KTibow** [comment]
How hard would it be to update the new files to add those 20 lines?

**Pull request closed without merging**
