### PR TITLE
Create Hackname.java

### PR DESCRIPTION
**Pull request by nofh428**
## Description
What have you added and what does it do? (Alternatively, what have you fixed and how does it work?)

## (Optional) screenshots / videos
If applicable, add screenshots or videos to help explain your pull request.

### CODE REVIEW

**Comment by Lamby777** [comment]
what

**Comment by nofh428** [comment]
iGNORE THIS

**Comment by nofh428** [comment]
i accidently made this lol
how to delete

**Comment by nofh428** [comment]
done

**Pull request closed without merging**
