### PR TITLE
Waypoints

### PR DESCRIPTION
**Pull request by AlibifortheAfterlife**
Added a simple waypoint system.

-Keybinds to add and delete waypoints (default NUM+ and NUM- respectively).

-Keybinds to scroll through the list of waypoints for the world you're currently in
  (default NUM* for up and NUM/ for down)

-Keybind to toggle (default NUM9)

-Keybinds are disabled if VoxelMap is loaded to free up keyboard real estate.

-Dot commands to add and delete waypoints or clear the whole list(server and world specific).

-New click gui window to manage waypoints(LClick to select, RClick to delete)

-HUD element that shows the selected waypoint and distance from it.

-Slider settings to change color.

-Waypoint markers render a fixed distance away from the player until you're close to the waypoint so they never go out of render distance. 
  To make this work, I added a new util method to RotationUtils that returns a Vec3d representing a point along a the line between two Vec3ds a set distance away from whichever Vec3d you pass as your origin (the player, for example).

Also, as a consequence of how I implemented this, the Hack class now has a default method "processCmd" which allows extraneous keybinds. There is probably a better way to do this but I haven't spent enough time working with this client to know how yet.

### CODE REVIEW

**Comment by lasnikprogram** [comment]
Is the waypoint still acessible if it is out of render distance?

**Comment by princefl** [comment]
I'm new here, how do I download this?

**Comment by AlibifortheAfterlife** [comment]
> I'm new here, how do I download this?

If you're using Github Desktop and you've already forked or cloned the Wurst repo, just pick this pull request in the branch dropdown menu.
If you aren't, you'll have to fetch and checkout the pull request in CLI. There's tutorials online for how to do that.

**Comment by etienneschalk** [comment]
Hi, is it planned for this feature to be merged?

**Review by InfinitePower563 — APPROVED** [review]
Cool

**Pull request closed without merging**
