### PR TITLE
Add a new CrystalAura hack and .disconnect command

### PR DESCRIPTION
**Pull request by mccraft123456**
## Description
What have you added and what does it do? (Alternatively, what have you fixed and how does it work?)
I've added a CrystalAura hack. This is a hack that basically automatically attacks end crystals for you.
I've also added a .disconnect command. It basically disconnects from a server.

## (Optional) screenshots / videos
If applicable, add screenshots or videos to help explain your pull request.

### CODE REVIEW

**Comment by Loxeris** [comment]
.leave is already a thing

**Comment by pilotjoker999** [comment]
yea

**Comment by pilotjoker999** [comment]
but crystal aura is not

**Comment by pilotjoker999** [comment]
I believe that crystalaura is a good addition

**Comment by Loxeris** [comment]
True, crystal aura would be pretty neat. Just .disconnect is useless

**Comment by pilotjoker999** [comment]
@mccraft123456 I think that if you add a few  more lines, you can make a dupe command

**Comment by lasnikprogram** [comment]
You should check if the player has an weakness effect. Otherways you keep hitting the crystal without doing anything. Propably would cause some problems

**Comment by Loxeris** [comment]
weakness prevent crystal explosions ?? I never seen that, even snowballs make them explode. @lasnikprogram

**Comment by lasnikprogram** [comment]
Check this out https://youtu.be/xeI3x1PhV8Y?t=412

**Comment by Loxeris** [comment]
Very interesting, didn't know. Wiki lied to me :
> End crystals explode when attacked or damaged in most ways, even by attacks that normally do zero damage.

**Comment by BleachDrinker420** [comment]
I dunno man, crystalaura kinda looks identical to: https://github.com/BleachDrinker420/bleachhack-1.14/blob/7865162dfe4b4dd8cf9a81f5718de30336c0ffe4/BleachHack-Fabric-1.16/src/main/java/bleach/hack/module/mods/CrystalAura.java
please add credit

**Comment by mccraft123456** [comment]
@BleachDrinker420 crystalaura looks identical?

**Comment by mccraft123456** [comment]
kinda but that's like the only way I can even get this to work. Other ways I've tried will just either crash the client or just not function

**Comment by mccraft123456** [comment]
@BleachDrinker420 I've added the credit

**Comment by pilotjoker999** [comment]
hi mccraft123456, idk if ur still active, but I just want to tell you I have made a new pull request. I also re-coded ur crystalaura and removed that .disconnect command.

**Comment by Mhowser** [comment]
are you gonna close this now?

**Pull request closed without merging**
