### PR TITLE
Add setting to AutoToolHack for silk touching glowstone

### PR DESCRIPTION
**Pull request by bram-pkg**
A setting that enabled mining glowstone with silk touch, if a silk touch tool is available.

I can't figure out which formatter you are using, sorry for the mess. I'll gladly format with a different code style if you provide me with one.

### CODE REVIEW

**Comment by Alexander01998** [comment]
Here you go: https://github.com/Wurst-Imperium/Wurst7/files/5543756/Wurst7.code.style.settings.zip

Should probably make it use silk touch for every block that requires it, rather than just glowstone.

**Comment by bramceulemans** [comment]
I can add that, yes. I'll be sure to extend the method to include other
blocks with silk touch.

**Comment by bramceulemans** [comment]
One problem, some blocks that require silk touch don't have a higher mining
speed when breaking with a tool (like glowstone). How do you suggest this
is implemented?

**Comment by Alexander01998** [comment]
Any tool will do for now.

**Comment by bramceulemans** [comment]
In that case I'll just keep the existing logic that grabs the first
available tool with silk touch.

**Comment by bramceulemans** [comment]
I added all blocks that don't require a specific silk touch tool.

**Pull request closed without merging**
