### PR TITLE
Rebrand

### PR DESCRIPTION
**Pull request by pierluigizagaria**
## Description
Changed logo and removed the one in the options button.

## Screenshots
wurst_200

### CODE REVIEW

**Comment by cdxc** [comment]
wow nice

**Comment by ItsYoungDaddy** [comment]
Now this is interesting!

**Review by FlorianMichael — APPROVED** [review]

**Review by InfinitePower563 — COMMENTED** [review]
But why?

**Comment by Alexander01998** [comment]
Hey @pierluigizagaria,

While I appreciate the effort taken to create this pull request, I have no plans of rebranding the Wurst Client at the moment. The current logo fits well with the brand's identity and is widely recognizable among the user base.

Thanks for your understanding.

**Pull request closed without merging**
