### PR TITLE
Added tracers to SearchHack 

### PR DESCRIPTION
**Pull request by cdxc**
## Description
Added an option to the SearchHack module that draws tracers to the blocks the user is searching for. I also changed the default block to nether_portal, since its the most wildely used in this type of hack.

Without tracers cheked:

With tracers checked:

### CODE REVIEW

**Comment by Lamby777** [comment]
epic gamer

**Review by FlorianMichael — APPROVED** [review]

**Review by InfinitePower563 — APPROVED** [review]
Great addition, is very useful to search, especially if you want to want to know what direction the block is in.

**Comment by cdxc** [comment]
one year aniversary of this pull request, still nothing. i made a perfectly useful feature just out of my love for free software and this client.  i wanted to help, i helped. what i do now? idk! cry? cry a lot? sure. but my  tracers still won't be in the master. i could have just not done it. but i have. you could at least tell me my code was shit, but nothing :((((

**Comment by Lamby777** [comment]
No clue why, this would be a really useful change.

**Comment by FlorianMichael** [comment]
I also like the function and find it a pity that Alexander doesn't look at most pull requests or doesn't merge them, but that seems to be a general thing with him and is nothing personal.

**Comment by Lamby777** [comment]
still relevant (though has merge conflicts)

**Comment by cdxc** [comment]
hello, don't know if i can still write here, but i'm back and willing to discuss this. 

some users use this hack to find  blocks and in lower quantites, and most other clients offer this feature under the search hack, so i see no reason why  not at least offer this as a togglable feature.  

The nether portal is just an arbitrary block which i've seen as the default in other clients.

Also what excactly do you mean by "implementing them from scratch"? To make another seperate hack Tracers or something?  i would be willing to do any of this.

**Pull request closed without merging**
