### PR TITLE
Fix scrolling past default GUI end causes crash

### PR DESCRIPTION
**Pull request by nitram509**
## Description
Fixes issue #182.
I added some checks before accessing the list.

## (Optional) screenshots / videos
not applicable.

### CODE REVIEW

**Comment by Alexander01998** [comment]
Issue #183 is about an OptiFine crash. Did you mean #182?

**Comment by nitram509** [comment]
> Issue #183 is about an OptiFine crash. Did you mean #182?

You're right. Just a typo. I meant #182 "scrolling ... causes crash", indeed.

**Comment by Alexander01998** [comment]
Have you been able to reproduce the crash? I can't seem to "scroll past the normal limit" as it says in #182.

**Comment by nitram509** [comment]
Hi,

nope, just was watching the sources ... and from what I saw and according to my Java experience, this might happen.
Hence, I did add this "fencing" clause.

**Comment by nitram509** [comment]
The stack traces are clear, so I recommend to add such fencing.
It does no harm, no?

**Comment by Alexander01998** [comment]
> It does no harm, no?

From looking at the source code, it looks like it might cause the GUI to get stuck in the expanding animation. That's why I want to test it first.

**Pull request closed without merging**
