### PR TITLE
add instructions of how to set up the project in intellij idea

### PR DESCRIPTION
**Pull request by pilotjoker999**
## Description
What have you added and what does it do? (Alternatively, what have you fixed and how does it work?)
I did not add anything or fix anything, I just updated README.md so that people can understand how to set up this project in IntelliJ IDEA IDE because currently, this only shows how to set this up in Eclipse IDE. Since some people use IntelliJ, I think it is necessary to update README.md.

## (Optional) screenshots / videos
If applicable, add screenshots or videos to help explain your pull request.

### CODE REVIEW

**Comment by Alexander01998** [comment]
What about running `gradlew genSources` and fixing Idea's Gradle settings? That should also be necessary according to the Fabric Wiki: https://fabricmc.net/wiki/tutorial:setup

**Comment by pilotjoker999** [comment]
No, from what I know, that is not necessary. I've always used IntelliJ to contribute and I don't see any problem, and I always do not do that. In fact, IntelliJ actually generates the sources automatically in its import process, and that is why I also recommend IntelliJ to code and not Eclipse. You can try this out for yourself. I might be wrong though since I am on an older version of IntelliJ(2019.3) and the latest stable release is 2020.2 and the latest preview is 2020.3. Probably in the newer versions, changes have been made, but I'm not entirely sure.

**Comment by wurstisgood** [comment]
> No, from what I know, that is not necessary. I've always used IntelliJ to contribute and I don't see any problem, and I always do not do that. In fact, IntelliJ actually generates the sources automatically in its import process, and that is why I also recommend IntelliJ to code and not Eclipse. You can try this out for yourself. I might be wrong though since I am on an older version of IntelliJ(2019.3) and the latest stable release is 2020.2 and the latest preview is 2020.3. Probably in the newer versions, changes have been made, but I'm not entirely sure.

i am using 2020.2 and dont face any problems like gradle

**Comment by Mersid** [comment]
You can run `gradlew genSources idea` and then open the project using the generated .ipr file, if opening the project by using Gradle is causing issues. It's how I do it.

**Comment by pilotjoker999** [comment]
@Mersid Which version are you using? For me, it works even without running the commands.

**Pull request closed without merging**
