### PR TITLE
Turkish translations are here!

### PR DESCRIPTION
**Pull request by alfredsaveron**
🥳 English to Turkish translated words and sentences are here, I hope this helps.

### CODE REVIEW

**Comment by Git-North** [comment]
Hello I'm a local Turkish speaker and I spotted a few descriptions that doesn't exactly translate correctly such as "autobuild" being translated as "iş" rather than "oto-inşa/otomatik-inşa"

User likely used a translator such as Google translate

**Comment by Git-North** [comment]
There are also sentences that just does not make sense

**Review by Git-North — CHANGES_REQUESTED** [review]
User clearly used a translation service

Fix incorrect translations

**Comment by alfredsaveron** [comment]
> Hello I'm a local Turkish speaker and I spotted a few descriptions that doesn't exactly translate correctly such as "autobuild" being translated as "iş" rather than "oto-inşa/otomatik-inşa" (Iş means a job or an action) User likely used a translator such as Google translate

Thanks, I'lll fix them as soon as possible. Again, thx for the good review.

**Comment by Git-North** [comment]
> > Hello I'm a local Turkish speaker and I spotted a few descriptions that doesn't exactly translate correctly such as "autobuild" being translated as "iş" rather than "oto-inşa/otomatik-inşa" (Iş means a job or an action) User likely used a translator such as Google translate
> 
> 
> 
> Thanks, I'lll fix them as soon as possible. Again, thx for the good review.

Hello I made a translation using your file as a template there are also a few translations that are not necessary but makes it easier to understand

I can just add it here

**Comment by Git-North** [comment]
re-opening this since I made a file

**Pull request closed without merging**
