### PR TITLE
Add gradle CI

### PR DESCRIPTION
**Pull request by ChillerDragon**
## Description
Add github action that builds on linux. This runs automatic on every commit to master or pullrequest. It makes it easier to ensure that this repository builds fine :)
Build errors in community pullrequests can be spotted in seconds

## screenshots

image
image

### CODE REVIEW

**Comment by JamesTheAwesomeDude** [comment]
That looks really awesome — does it produce working compiled artifacts we can drop in the mods folder?

I know one of the "bantz" currently online in the chat is which anarchy clients are discreetly compiled with unpublicized RAT modules; having a trusted third-party such as GitHub do the conversion from publicly-available-source to usable-mod-file would give Wurst a serious leg up on this topic.

**Comment by ChillerDragon** [comment]
> That looks really awesome — does it produce working compiled artifacts we can drop in the mods folder?
> 
> I know one of the "bantz" currently online in the chat is which anarchy clients are discreetly compiled with unpublicized RAT modules; having a trusted third-party such as GitHub do the conversion from publicly-available-source to usable-mod-file would give Wurst a serious leg up on this topic.

Uhm this is more ment as a compile check. The build binarys can be pushed to artifacts they then stay there for some while but not for ever. I can look into it and add it to the yaml. Regarding the trust topic... users now have to trust the wurst developers and microsoft. One should read the code and then self compile it.

**Comment by ChillerDragon** [comment]
Okay that now uploads artifacts. I am not sure what exactly you want in there. Is the resources directory needed?

You can download the zip here https://github.com/ChillerDragon/Wurst7/actions/runs/574994876

```
$ unzip Wurst7.zip
Archive:  Wurst7.zip
  inflating: Wurst-Client-v7.9-MC1.16.4-dev.jar
  inflating: Wurst-Client-v7.9-MC1.16.4-sources-dev.jar
  inflating: Wurst-Client-v7.9-MC1.16.4-sources.jar
  inflating: Wurst-Client-v7.9-MC1.16.4.jar

```

**Comment by Alexander01998** [comment]
Hi, thanks for the PR. I've now added a [similar script](https://github.com/Wurst-Imperium/Wurst7/blob/master/.github/workflows/gradle.yml) by combing bits of this and #347.

**Pull request closed without merging**
