### PR TITLE
Add BlockListSetting to SearchHack

### PR DESCRIPTION
**Pull request by bramceulemans**
## Description
What have you added and what does it do? (Alternatively, what have you fixed and how does it work?)

I was missing the feature that allows you to select multiple blocks in SearchHack.

### CODE REVIEW

**Comment by bramceulemans** [comment]
May I ask why this was closed?

**Comment by Alexander01998** [comment]
It seems like this was automatically closed when I deleted the v7.11 branch.

GitHub is not letting me reopen it. 
image

**Comment by bramceulemans** [comment]
In that case I'll rebase to master and re-open this, if that's alright with
you?

**Comment by Alexander01998** [comment]
👍

**Pull request closed without merging**
