### PR TITLE
new hack: TpsDisplayHack

### PR DESCRIPTION
**Pull request by isjerryxiao**
## Description
Add a TPS meter

## (Optional) screenshots / videos
image

### CODE REVIEW

**Review by InfinitePower563 — APPROVED** [review]

**Comment by isjerryxiao** [comment]
@Alexander01998 video showcase for all 4 pull requests: https://pb.meson.cc/s/loprhw2f.mp4

**Comment by buiawpkgew1** [comment]
@isjerryxiao please fix 22w16b
image

**Comment by Alexander01998** [comment]
@buiawpkgew1 Wurst itself hasn't even updated to 22w16b yet. Besides, this PR targets 1.18.2.

**Comment by Cyclopropinon** [comment]
when will this be actually added to wurst?
(when will this branch merge?)

**Pull request closed without merging**
