### PR TITLE
Add cocoa support to AutoFarmHack

### LINKED ISSUE #283: AutoFarm: cocoa isn't supported
## Description
Cocoa pods aren't supported by AutoFarm

## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. Plant cocoa
2. Enable AutoFarm
3. Wait till maturity

## Screenshots / Videos (Optional)

Pre-maturity (there's no blue lozenge):

Upon maturity (not being farmed):

## Crash Report
Please find your crash report file at "%appdata%/.minecraft/crash-reports", open the file in a text editor and copy-paste its content below.

```

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 1/20/21, 10:04 PM
Description: Manually triggered debug crash

java.lang.Throwable
	at net.minecraft.class_309.method_1474(class_309.java:458)
	at net.minecraft.class_310.method_1574(class_310.java:1609)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_309.method_1474(class_309.java:458)

-- Affected level --
Details:
	All players: 1 total; [class_746['squeegily'/20321360, l='ClientLevel', x=-56121.79, y=71.00, z=58686.83]]
	Chunk stats: SodiumChunkCache: 121
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,120,0), Chunk: (at 0,7,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 98637 game time, 266771651 day time
	Server brand: Waterfall <- endcrystal.me§r
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:699)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 5.9.16-100.fc32.x86_64
	Java Version: 11.0.9.1, Red Hat, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Red Hat, Inc.
	Memory: 1042964752 bytes (994 MB) / 2181038080 bytes (2080 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 4
	JVM Flags: 8 total; -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		appleskin: AppleSkin 1.0.11
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.8.1
		fabric: Fabric API 0.29.4+1.16
		fabric-api-base: Fabric API Base 0.2.0+daa38b3d7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.0.10+ca58154a7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.10+ca58154a7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.2+ca58154a7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.2+ca58154a7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.3+ca58154a7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.1+ca58154a7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.1
		java: OpenJDK 64-Bit Server VM 11
		minecraft: Minecraft 1.16.5
		modmenu: Mod Menu 1.14.13+build.19
		nbttooltip: NBT Tooltip 1.0.6-fabric
		sodium: Sodium 0.1.0
		wurst: Wurst Client v7.10-MC1.16.5
		xaerominimap: Xaero's Minimap 21.1.0
		xaeroworldmap: Xaero's World Map 1.11.9
	Launched Version: fabric-loader-0.11.1-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD TURKS (DRM 2.50.0 / 5.9.16-100.fc32.x86_64, LLVM 10.0.1) GL version 3.1 Mesa 20.2.3, X.Org
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz

```

### PR DESCRIPTION
**Pull request by JamesTheAwesomeDude**
## Description
Fixes #283

I templated it off 591ec9d6b79a74e5301931c9e7ebbcbc35145e7b, but I do not have a development environment, so I have not been able to test it.

### CODE REVIEW

**Comment by Alexander01998** [comment]
This would only harvest cocoa, but not replant it. Is that why this is marked as a draft?

**Comment by JamesTheAwesomeDude** [comment]
> This would only harvest cocoa, but not replant it. Is that why this is marked as a draft?

Essentially, yes.

I can't figure out where the API reference is to figure out what block belongs [here](https://github.com/Wurst-Imperium/Wurst7/blob/b5152159163a1b6ef30369d0dae988a56628d2e2/src/main/java/net/wurstclient/hacks/AutoFarmHack.java#L319):

```java
	private boolean canBeReplanted(BlockPos pos)
	{
		Item item = plants.get(pos);
		
		if(item == Items.WHEAT_SEEDS || item == Items.CARROT
			|| item == Items.POTATO || item == Items.BEETROOT_SEEDS
			|| item == Items.PUMPKIN_SEEDS || item == Items.MELON_SEEDS)
			return BlockUtils.getBlock(pos.down()) instanceof FarmlandBlock;
		
		if(item == Items.NETHER_WART)
			return BlockUtils.getBlock(pos.down()) instanceof SoulSandBlock;

		if(item == Items.COCOA_BEANS)
			return BlockUtils.getBlock(pos.north()) instanceof JungleLogBlock
			|| BlockUtils.getBlock(pos.east()) instanceof JungleLogBlock
			|| BlockUtils.getBlock(pos.south()) instanceof JungleLogBlock
			|| BlockUtils.getBlock(pos.west()) instanceof JungleLogBlock;
		
		return false;
	}
```

`JungleLogBlock` in the above is a **complete guess**; I don't know where to find the reference files for that list.

**Comment by JamesTheAwesomeDude** [comment]
And, actually, I'm still a bit foggy on b5152159163a1b6ef30369d0dae988a56628d2e2, too.

As best as I could tell, the block form is `Blocks.COCOA` and the item form is `Items.COCOA_BEANS`, but that's also not validated by any documentation I could find.

**Comment by JamesTheAwesomeDude** [comment]
https://www.spigotmc.org/threads/getblock-getdata-for-detecting-log-type.281241/#post-2732383

Looks like it might be more than a simple `instanceOf` check in this case

**Comment by Alexander01998** [comment]
I can confirm that this works.

**Comment by Alexander01998** [comment]
> `JungleLogBlock` in the above is a **complete guess**; I don't know where to find the reference files for that list.

You can check that in the source code of `net.minecraft.block.Blocks`:

```java
JUNGLE_LOG = register("jungle_log", createLogBlock(MaterialColor.DIRT, MaterialColor.SPRUCE));
```

```java
private static PillarBlock createLogBlock(MaterialColor topMaterialColor, MaterialColor sideMaterialColor) {
  return new PillarBlock(AbstractBlock.Settings.of(Material.WOOD, (blockState) -> {
    return blockState.get(PillarBlock.AXIS) == Direction.Axis.Y ? topMaterialColor : sideMaterialColor;
  }).strength(2.0F).sounds(BlockSoundGroup.WOOD));
}
```

As you can see, there is no separate class for jungle logs. All logs are created as instances of `PillarBlock`, which isn't very helpful for doing `instanceof` checks.

In this case, it's better to use `==` with `Blocks.JUNGLE_LOG`, as you did.

**Pull request merged**
