### PR TITLE
new hack: AutoMLGHack

### PR DESCRIPTION
**Pull request by isjerryxiao**
## Description
It does auto mlg water bucket and powder snow.

### CODE REVIEW

**Review by InfinitePower563 — CHANGES_REQUESTED** [review]
So far, a short fall distance fails to reduce/negate damage. Also, the player drops straight down whether or not the player has a MLG-able item in their inventory, and items in the offhand are not detected. Otherwise works.

**Comment by isjerryxiao** [comment]
@InfinitePower563 Placing water bucket in your offhand is generally not a good idea since you're likely to interact with the item in your main hand instead of placing water down, making the whole thing much more unreliable.

**Comment by isjerryxiao** [comment]
Now the hack can make use of offhand or inventory. Also the short fall distance issue is fixed.

**Comment by buiawpkgew1** [comment]
@isjerryxiao https://github.com/Wurst-Imperium/Wurst7/pull/559，https://github.com/Wurst-Imperium/Wurst7/pull/558，https://github.com/Wurst-Imperium/Wurst7/pull/557和https://github.com/Wurst-Imperium/Wurst7/pull/556为啥不放在一起？

**Comment by isjerryxiao** [comment]
@buiawpkgew1 https://github.com/Wurst-Imperium/Wurst7#note-about-pull-requests

**Comment by buiawpkgew1** [comment]
好的

**Review by InfinitePower563 — CHANGES_REQUESTED** [review]
Now it activates when elytra is activated. Kind of glitches out when gliding downward.

**Comment by isjerryxiao** [comment]
You can't use elytra with NoFall either, but adding a check is better.

**Comment by isjerryxiao** [comment]
https://github.com/Wurst-Imperium/Wurst7/pull/557/commits/c7143709782cd0b1aafb39b810cafec4b9c7e7f9#diff-c15d2912e3bdecdda8ec550d8328b3791d5a20795a882afb85c0614c67ec8986R155

**Comment by wb1016** [comment]
```
C:\Users\wb\minecraft\Wurst7\src\main\java\net\wurstclient\hacks\AutoMLGHack.java:134: error: cannot find symbol
                    WURST.getHax().autoEatHack.pauseEat = 20;
                                              ^
  symbol:   variable pauseEat
  location: variable autoEatHack of type AutoEatHack
```
cant build anymore

**Pull request closed without merging**
