### PR TITLE
Added a HUD

### PR DESCRIPTION
**Pull request by toth-boldizsar**
Added a HUD to display things like coordinates, speed, FPS and TPS.

## Description
Display a HUD like in many other clients, showing coordinates, speed, FPS and TPS

## (Optional) screenshots / videos
image

### CODE REVIEW

**Comment by Titaniumtown** [comment]
Why was this closed?

**Comment by Alexander01998** [comment]
And why was an unrelated AutoClicker added to this?

**Comment by toth-boldizsar** [comment]
> Why was this closed?

Because I realised that part of it doesn't work.

> And why was an unrelated AutoClicker added to this?

Ohh that's because I'm not really good at using github.

**Comment by toth-boldizsar** [comment]
I moved the AutoClicker to a new branch and remvoved the TPS, because it wasn't working.

**Pull request closed without merging**
