### PR TITLE
Update uk_ua.json

### PR DESCRIPTION
**Pull request by Ultra119**
## Description
Updated Ukraininan translation

### CODE REVIEW

**Comment by Alexander01998** [comment]
Hey @KTibow @xVirum @MrYotic @faseri 

Do any of you have some time to vote on these Ukrainian translations?
https://crowdin.com/proofread/wurst7/all/en-uk?filter=basic&value=5
(The ones listed under my name are copied from this pull request.)

**Comment by KTibow** [comment]
Probably should mention that I'm not Ukrainian, I just helped with getting the translations into Github.

**Comment by Alexander01998** [comment]
Oh, OK. Sorry about that.

**Comment by xVirum** [comment]
Hi, I just translated the 2 remaining functions, in NoLevitation I replaced
the word "when" with "if", because in our language people perceive it
better. 2 mistakes because Crowdin doesn't understand the word Shulker and
doesn't know what the word "§c§lWARNING" is.

There is a grammatical error in NewChunks because there is no word "chunks"
in formal Ukrainian, but everyone calls them that, so why not)

сб, 1 окт. 2022 г. в 20:16, Alexander01998 ***@***.***>:

**Comment by Alexander01998** [comment]
Thanks!

**Pull request merged**
