### PR TITLE
KnockbackPlus hack

### PR DESCRIPTION
**Pull request by Beta-51**
## Description
KnockbackPlus, makes your knockback just a little bit stronger. With knockback 2, you can push enemies up to 10+ blocks away with one single hit.

## (Optional) screenshots / videos
no videos or screenshots sorry

### CODE REVIEW

**Review by feliscatusmeows — APPROVED** [review]
UwU OwO OwO UwU
Question: will this cause me to become hungry since it sends a start sprinting packet but it doesn't stop sprinting?

**Comment by Alexander01998** [comment]
> Question: will this cause me to become hungry since it sends a start sprinting packet but it doesn't stop sprinting?

I think so. I might need to add a `STOP_SPRINTING` packet before merging this.

**Comment by SirEnder125** [comment]
Question. Will this even be useable? It seems to good to be true. What servers could I use such a cheat on without instantly being kicked/banned mid-game of bedwars or whatever?

**Comment by feliscatusmeows** [comment]
Basically a sprint hit causes more knockback, so this hack pretends you're sprinting using packets to cause extra knockback, this may or may not work on different servers and will not work with criticals

**Comment by CheatMaker** [comment]
> Question. Will this even be useable? It seems to good to be true. What servers could I use such a cheat on without instantly being kicked/banned mid-game of bedwars or whatever?

Why are you using wurst anyways lmao. For free client use liquidbounce or nightX

**Comment by feliscatusmeows** [comment]
Those are both 1.8 forge(lb fabric is still quite unstable)
Wurst 7 is a fabric client for the latest versions, and often updates for weekly snapshots. Also unlike those clients, wurst has the amazing .taco hack.

**Comment by Alexander01998** [comment]
Sorry, I'm not planning to add this anymore.

**Pull request closed without merging**
