### PR TITLE
TrailHack

### PR DESCRIPTION
**Pull request by lasnikr**
Added a new Hack. The trail hack. It has some customizations
image

### CODE REVIEW

**Comment by code1dot** [comment]
Oh man, this is awesome

**Comment by BleachDrinker420** [comment]
poggers, directly skidded from bleachhack just without any customization

**Comment by Alexander01998** [comment]
> poggers, directly skidded from bleachhack just without any customization

I have found this file: https://github.com/BleachDrinker420/bleachhack-1.14/blob/983da875e58e530b732f87ac314a8f497acf5e8b/BleachHack-Fabric-1.15/src/main/java/bleach/hack/module/mods/Trail.java

which is about a month older and looks similar to the file in this Pull Request.
It seems plausible that this PR is an edited version of that file.

Their GPLv3 license would be compatible to ours (meaning it would be legal to merge this PR into Wurst),
but still Lasnik should have mentioned if it's taken from another repository.

I'll leave it up to @lasnikprogram and @BleachDrinker420 to come to an agreement about this.

Let me know afterwards if this can be merged...

**Comment by BleachDrinker420** [comment]
Tbh i don't really care that much, just add credit to me or my client

**Comment by lasnikprogram** [comment]
Yeah it was copied and slightly modified.
I am sorry. Forgot the credit to @BleachDrinker420

**Comment by lasnikprogram** [comment]
This was clarified with BleachDrinker420 via Discord

**Comment by wurstisgood** [comment]
is it implemented???

**Review by FlorianMichael — COMMENTED** [review]
nice!

**Pull request closed without merging**
